version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: backend-test-postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - testPostgresData:/var/lib/postgresql/data
    networks:
    - database

volumes:
  testPostgresData:

networks:
  database:
    name: database
    